name: dart-openctm
version: 1.0.0
description: >
  A port of js-openctm to Dart
dependencies:
  lzma.dart:
    git: 
      url: git://github.com/nelsonsilva/dart-lzma.git
      ref: dev
  fixnum:
    sdk: fixnum
